application:
  database:
    expired:
      time: ${EXPIRED_DATA} # Clean expired URL's
  redis:
    default:
      time:
        shortUrl: "10m"
        userSessions: "1h"
    sheduled:
      connection:
        time: ${REDIS_CONNECTION} # Check if the redis are connected on system.
      syncronization:
        time: ${REDIS_SYNC} # Syncronize the data with the user count from the redis to database
  security:
    jwt:
      secret-key: ${SECRET-KEY}

spring:
  security:
    user: 
      name: admin
      password: ${SECURITY_PASSWORD}
