spring:
  profiles:
    active: log, database, service, prometheus # log, debug, database, service
  application:
      name: URLShortener

server:
  port: ${SERVER_PORT:8000}
  servlet:
    context-path:
