spring:
  profiles:
    active: log, database, service # log, debug, database, service
  application:
      name: UrlShortener

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  port: ${SERVER_PORT:8000}
  servlet:
    context-path:
