global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'shortUrl'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:${SERVER_PORT:8000}']
      
remote_write:
  - url: "${REMOTE_WRITE_URL}"
    sigv4:
      region: "{PROMETHEUS_REGION}"
    queue_config:
      max_samples_per_send: 500
      max_shards: 10
      capacity: 500